### PR TITLE
Fix unselecting api-selected row bug

### LINKED ISSUE #85: Data Table: weird behavior with deselecting rows as a user that were set by the API
Consider the following

    const feed = hx.dataTable.objectFeed({
      headers: [
        { name: 'Name', id: 'name' },
        { name: 'Age', id: 'age' },
        { name: 'Profession', id: 'profession' }
      ],
      rows: [
         {
           id: 0, // hidden details can go here (not in the cells object)
           cells: { 'name': 'Bob', 'age': 25, 'profession': 'Developer' }
         },
         {
           id: 1,
           cells: { 'name': 'Jan', 'age': 41, 'profession': 'Artist' }
         },
         {
           id: 2,
           cells: { 'name': 'Dan', 'age': 41, 'profession': 'Builder' }
         }
      ]
    })
    const tableSel = hx.detached('div')
    const table2 = new hx.DataTable(tableSel.node(), {feed: feed, singleSelection: true, selectEnabled: true})
    table2.selectedRows([0])
    table2.on('selectedrowschange', (data) => data.cause === 'user' ? console.log(data.value) : undefined)
    hx.select('#example').append(tableSel)

Everything seems fine ?

Now try deselecting a row by clicking on it!

It doesn't get deselected.

Also `[0]` is logged, I would expect `[]`.

Clicking it a second time "works", so all the user sees is a slow page.

### PR DESCRIPTION
**Pull request by georgesimms**
fixes #85 . The issue is selectRow clears the selection if @_lastSelected is different from the row you want to select and single selection is enabled, but @_lastSelected isn't set by hx.DataTable::selectedRows.

### CODE REVIEW

File: modules/data-table/main/index.coffee [hunk 1]
```diff
@@ -236,7 +236,9 @@ class DataTable extends hx.EventEmitter
       if @singleSelection() and hx.isArray(value) and value.length
         value = [value[0]]
       @_.selectedRows = new hx.Set(value)
-      @emit('selectedrowschange', {value: @_.selectedRows.values(), cause: 'api'})
+      newSelectedRows = @_.selectedRows.values()
+      @emit('selectedrowschange', {value: newSelectedRows, cause: 'api'})
+      @_.lastSelected = newSelectedRows[newSelectedRows.length - 1]
```
Comment (georgesimms) [inline modules/data-table/main/index.coffee]: this is the salient line. It sets @_.lastSelected when the selected rows were changed by the API

File: modules/data-table/test/spec.coffee [hunk 2]
```diff
@@ -688,6 +692,35 @@ describe 'data-table', ->
...
+        table.selectedRows [0]
+        
+        table.on 'selectedrowschange', (data) ->
+          if data.cause is 'user'
+            # Row 0 was selected before, so now we're unselecting it
+            data.value.should.eql []
+            done()
+        checkSel = tableSel.select '.hx-sticky-table-wrapper .hx-data-table-checkbox'
+        faker = fakeNodeEvent checkSel.node()
+        faker fakeEvent
```
Comment (georgesimms) [inline modules/data-table/test/spec.coffee]: regression test for bug
