### PR TITLE
#370: Resolves y bounds calculation

### LINKED ISSUE #370: Plot: automatic calculation of ymax does not work when there are multiple series and the data is sparse
## Context
The following stacked bar chart:

```js
const hx = window.hx

const graphSel = hx.graph({
  axes: [{
    x: {
      scaleType: 'discrete'
    },
    y: {
      min: 0
    },
    series: [
      {
        type: 'bar',
        options: {
          title: 'Bob',
          group: 'g0',
          fillColor: hx.theme.plot.coldCol,
          data: [{
            x: 'verybig',
            y: 10
          }, {
            x: 'alwayspresent',
            y: 1
          }]
        }
      },
      {
        type: 'bar',
        options: {
          title: 'Lazlo',
          fillColor: hx.theme.plot.warmCol,
          group: 'g0',
          data: [{
            x: 'alwayspresent',
            y: 2
          }]
        }
      }
    ]
  }]
})

hx.select('#root').add(hx.detached('div').class('hx-content').add(graphSel))
```

## Expected Behavior
The calculated y max value should be 10

## Actual Behavior
The calculated y max value is actually 3

## Possible Fix
The current y max value uses the "top series" to work out what all the x values are for the whole graph. It should get the x values for all series.

## Steps to Reproduce
Use the code above, it results in this screenshot:

screenshot from 2017-01-11 11-11-13

## Your Environment

* Hexagon Version: 1.9.0
* Browser Name and version: Chromium 55.0.2883.87 Built on Ubuntu , running on Ubuntu 16.04
* Operating System and version (desktop or mobile): Ubuntu (desktop) 16.04

### PR DESCRIPTION
**Pull request by georgesimms**
## Description
Y bounds calculation pulled out into its own method

Refactored to make it easier to follow (use Array::map, Array::reduce etc rather than coffeescript for loops)

Y bounds calculation not called when overridden by user manual config

Rather than using topseries, all the x values are got out of all the series

## Motivation and Context
Resolves #370 

## How Has This Been Tested?
Regression test added.
Tested visually with same example as in issue

## Screenshots (if appropriate):
Screenshot for example in issue:

screenshot from 2017-01-11 14-01-50

## Checklist:

- [x] I have added a tag to this pull request that indicates the impact of the change (patch, minor or major)
- [X] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly. (This includes updating the changelog).
- [X] I have read the **CONTRIBUTING** document.
- [X] All my changes are covered by tests.
- [ ] This request is ready to merge

### CODE REVIEW

File: modules/plot/main/coffee/Axis.coffee [hunk 1]
```diff
@@ -321,60 +318,20 @@ class Axis
...
     else
 
-      # OPTIM: this expensive calculation is not needed if the scales are non auto
-      # XXX: band series?
+      { yMinMightBeAuto, yMaxMightBeAuto } = { yMaxMightBeAuto: @y.max(), yMinMightBeAuto: @y.min() }
+      { ymin, ymax } = if 'auto' in [yMaxMightBeAuto, yMinMightBeAuto]
+        { ymin, ymax } = @calculateYBounds()
+        yminscaled = if yMinMightBeAuto is 'auto' then scalePad(ymin, ymax - ymin, -@y.scalePaddingMin()) else yMinMightBeAuto
+        ymaxscaled = if yMaxMightBeAuto is 'auto' then scalePad(ymax, ymax - ymin, @y.scalePaddingMax()) else yMaxMightBeAuto
+        { ymin: yminscaled, ymax: ymaxscaled }
```
Comment (georgesimms) [inline modules/plot/main/coffee/Axis.coffee]: only run this if either min or max are 'auto'

File: modules/plot/main/coffee/Axis.coffee [hunk 2]
```diff
@@ -321,60 +318,20 @@ class Axis
...
+      else
+        { ymin: yMinMightBeAuto, ymax: yMaxMightBeAuto }
 
-      ymin = undefined
```
Comment (georgesimms) [inline modules/plot/main/coffee/Axis.coffee]: code moved into its own method and refactored to use Array::reduce

File: modules/plot/main/coffee/Axis.coffee [hunk 3]
```diff
@@ -573,14 +530,67 @@ class Axis
...
-      for series, j in @series()
+      yStack = Math.max(yscaledomainmin, 0)
+      maybeys = allSeries.map (series) ->
         if series._.seriesId < seriesId and series.group() == group and series._.type == type
-          ys = series.getY(x, @x.scaleType() is 'discrete')
-          if hx.defined(ys)
-            yStack += ys
-      yStack
-    else Math.max(start, 0)
+          series.getY(x, xscaletype is 'discrete')
```
Comment (georgesimms) [inline modules/plot/main/coffee/Axis.coffee]: There is a slightly interesting pattern here I've noticed a couple of times where we map and then filter out undefined, to approximate something like scala's collect . I think labeling it like this makes it clearer what's going on

File: modules/plot/main/coffee/Axis.coffee [hunk 4]
```diff
@@ -573,14 +530,67 @@ class Axis
...
+      yStack + hx.sum maybeys.filter hx.identity
+    else
+      Math.max(start, 0)
+
+  calculateYBounds: ->
+    # The series must already be tagged before calling this method
+    # XXX: band series?
```
Comment (georgesimms) [inline modules/plot/main/coffee/Axis.coffee]: This comment was there before, I'm not sure if it still applies as we explicitly handle BandSeries below

File: modules/plot/main/coffee/Axis.coffee [hunk 5]
```diff
@@ -573,14 +530,67 @@ class Axis
...
+            extent(data, (d) -> d.y)
+        ys = maybeys.filter((d) -> d?)
+  
+        {
+          yymin: hx.min(ys.map((d) -> d[0]))
+          yymax: hx.max(ys.map((d) -> d[1]))
+        }
+      else
+        topSeries = series[series.length-1]
+        allX = hx.unique hx.flatten series.map (s) -> s.data().map ({ x }) -> x
```
Comment (georgesimms) [inline modules/plot/main/coffee/Axis.coffee]: get all the x, not just from the top series

File: modules/plot/main/coffee/Axis.coffee [hunk 6]
```diff
@@ -573,14 +530,69 @@ class Axis
...
+            if s instanceof StraightLineSeries
+              if not data.dx and not data.dy and data.y
+                [data.y, data.y]
+              else
+                undefined
+            else if s instanceof BandSeries
+              extent2(data, ((d) -> d.y1), (d) -> d.y2)
+            else
+              extent(data, (d) -> d.y)
+          ys = maybeys.filter((d) -> d?)
```
Comment (georgesimms) [inline modules/plot/main/coffee/Axis.coffee]: Another example of the "map and then filter" pattern

File: modules/plot/main/coffee/Axis.coffee [hunk 7]
```diff
@@ -573,14 +530,69 @@ class Axis
...
+          {
+            yymin: hx.min stackHeights
+            yymax: hx.max stackHeights
+          }
+        {
+          ymin: Math.min(ymin, yymin)
+          ymax: Math.max(ymax, yymax)
+        }
+  
+    stackGroupReductor = (prev, { type, group }) ->
```
Comment (georgesimms) [inline modules/plot/main/coffee/Axis.coffee]: we were not actually using the type before. We were pulling it out, but then assuming the topSeries type was the type for all series. So let's just use it directly

File: modules/plot/main/coffee/Axis.coffee [hunk 8]
```diff
@@ -573,14 +530,69 @@ class Axis
...
+    initValue = { ymin: 0, ymax: 0 }
+    types = hx.groupBy(allSeries, (d) -> d._.type)
+    stackGroups = types.map ([type, series]) ->
+      type: type
+      group: hx.groupBy series, (s) -> if supportsGroup(s) then s.group() else undefined
+  
+  
+    typeGroupReductor = (type) =>
+      ({ ymin, ymax }, [seriesGroup, series]) =>
+        { yymin, yymax } = if seriesGroup == undefined
```
Comment (georgesimms) [inline modules/plot/main/coffee/Axis.coffee]: again previously we were not actually using seriesGroup beyond checking if it was defined or not

now we use the value we already calculated rather than calculating one from topSeries and assuming it is representative

File: modules/plot/main/coffee/Axis.coffee [hunk 9]
```diff
@@ -573,14 +530,69 @@ class Axis
...
+          ys = maybeys.filter((d) -> d?)
+  
+          {
+            yymin: hx.min(ys.map((d) -> d[0]))
+            yymax: hx.max(ys.map((d) -> d[1]))
+          }
+        else
+          allX = hx.unique hx.flatten series.map (s) -> s.data().map ({ x }) -> x
+          stackHeights = allX.map (x) ->
+            maybeys = series.map (series) -> series.getY x, xscaletype is 'discrete'
```
Comment (georgesimms) [inline modules/plot/main/coffee/Axis.coffee]: There is not any point calling getYStack here as it pointlessly just filters over all the series in the graph

we already have the relevant series, so don't waste time filtering them again

File: modules/plot/main/coffee/Axis.coffee [hunk 10]
```diff
@@ -573,14 +530,69 @@ class Axis
...
+            hx.sum maybeys.filter hx.identity
+          {
+            yymin: hx.min stackHeights
+            yymax: hx.max stackHeights
+          }
+        {
+          ymin: Math.min(ymin, yymin)
+          ymax: Math.max(ymax, yymax)
```
Comment (georgesimms) [inline modules/plot/main/coffee/Axis.coffee]: ymax and ymin are always numbers now, so the checks for undefined have been removed

File: modules/plot/main/coffee/Axis.coffee [hunk 11]
```diff
@@ -573,14 +530,69 @@ class Axis
       xStack
     else Math.max(start, 0)
 
-  # gets the height of the stack for a particular type, group and x value (the seriesId is the series that you want to get the baseline for)
   getYStack: (type, group, x, seriesId, start = 0) ->
```
Comment (georgesimms) [inline modules/plot/main/coffee/Axis.coffee]: this is now only called by series, not within the axis itself

File: modules/plot/test/spec.coffee [hunk 12]
```diff
@@ -10,6 +10,49 @@ describe "plot", ->
...
+                  y: 2
+                }]
+              }
+            }
+          ]
+  		})
+
+        axis.tagSeries()
+        { ymax } = axis.calculateYBounds()
+        ymax.should.eql(10)
```
Comment (georgesimms) [inline modules/plot/test/spec.coffee]: regression test

File: modules/plot/main/coffee/Axis.coffee [hunk 13]
```diff
@@ -321,60 +318,20 @@ class Axis
...
-                if not data.dx and not data.dy and data.y
-                  [data.y, data.y]
-                else
-                  undefined
-              else if s instanceof BandSeries
-                extent2(data, ((d) -> d.y1), (d) -> d.y2)
-              else
-                extent(data, (d) -> d.y)
-            ys = ys.filter((d) -> d?)
+      { yMinMightBeAuto, yMaxMightBeAuto } = { yMaxMightBeAuto: @y.max(), yMinMightBeAuto: @y.min() }
```
Comment (c-frater) [inline modules/plot/main/coffee/Axis.coffee]: Not sure I'm keen on destructuring like this - you may as well do `yMinMightbeAuto = @y.min()`

File: modules/plot/main/coffee/Axis.coffee [hunk 14]
```diff
@@ -321,60 +318,20 @@ class Axis
...
-              ymax = 0
-            else
-              ymax = Math.max(ymax, 0)
-            for d in topSeries.data()
-              stackHeight = @getYStack(topSeries._.type, topSeries.group(), d.x, topSeries._.seriesId+1, @yScale.domainMin)
-              if (ymin == undefined or stackHeight < ymin) then ymin = stackHeight
-              if (ymax == undefined or stackHeight > ymax) then ymax = stackHeight
 
       ymin = if @y.min() is 'auto' then ymin else @y.min()
       ymax = if @y.max() is 'auto' then ymax else @y.max()
```
Comment (c-frater) [inline modules/plot/main/coffee/Axis.coffee]: Do we still need these lines? It looks like this logic is duplicated above

File: modules/plot/main/coffee/Axis.coffee (hunk 13 above)
Comment (georgesimms) [inline modules/plot/main/coffee/Axis.coffee]: yes, you are right that it is pointless.

Comment (georgesimms) [inline modules/plot/main/coffee/Axis.coffee]: removed

File: modules/plot/main/coffee/Axis.coffee (hunk 14 above)
Comment (georgesimms) [inline modules/plot/main/coffee/Axis.coffee]: You may well be right, I'd like to make a test just to make sure though.

I think the easiest way to tell a non-auto value is not ignored is by moving this logic into calculateYBounds and writing a test for it there.

Comment (georgesimms) [inline modules/plot/main/coffee/Axis.coffee]: I have removed it, and added tests for when y.min and y.max aren't auto.

File: modules/plot/main/coffee/Axis.coffee [hunk 15]
```diff
@@ -573,14 +519,73 @@ class Axis
...
-            yStack += ys
-      yStack
-    else Math.max(start, 0)
+          series.getY(x, xScaleType is 'discrete')
+      yStack + hx.sum maybeys.filter hx.identity
+    else
+      Math.max(start, 0)
+
+  calculateYBounds: (yMinMightBeAuto, yMaxMightBeAuto) ->
+    if 'auto' in [yMaxMightBeAuto, yMinMightBeAuto]
```
Comment (c-frater) [inline modules/plot/main/coffee/Axis.coffee]: +1 for moving this in here

**Comment by jmsmyth** [comment]
Seems like a bugfix to me, so this could be a patch release?
