### PR TITLE
#360 data table sort bugfix

### LINKED ISSUE #360: DataTable: filter ignored when sorting any column in descending order
## Context
Users complain that my data table 'loses' filter when they sort data

## Expected Behavior
Filter applies, only matching rows appear

## Actual Behavior
All rows are visible

## Steps to Reproduce
1. Open https://www.hexagonjs.io/docs/1.9.0/data-table/
2. In the first example type '41' to the filter field (you should see 2 of 3 rows)
3. Click any column 2 times to sort it in descending order

If the demo page works correct, the regression was introduced after version 1.4.2.

## Your Environment
* Hexagon Version: 1.9.0
* Browser Name and version: Chrome 55.0.2883.87 (64-bit) - also reproduced in Firefox 50.1.0
* Operating System and version (desktop or mobile): Kubuntu 16.10

### PR DESCRIPTION
**Pull request by c-frater**
## Description

Updated the object feed to use the same logic for advanced search and regular filters and added handling of the cached filter items.

## Motivation and Context

Resolves #360 

## How Has This Been Tested?

Added regression test and tested in browser

## Checklist:

- [x] I have added a tag to this pull request that indicates the impact of the change (patch, minor or major)
- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly. (This includes updating the changelog).
- [x] I have read the **CONTRIBUTING** document.
- [x] All my changes are covered by tests.
- [x] This request is ready to merge

### CODE REVIEW

File: modules/data-table/main/index.coffee [hunk 1]
```diff
@@ -1077,6 +1077,15 @@ getAdvancedSearchFilter = (cellValueLookup = hx.identity, termLookup = defaultTe
       not hx.defined invalidFilter
     hx.defined validFilters
 
+
+getFiltered = (rows, term, filtered, filterCacheTerm, fn) ->
```
Comment (jmsmyth) [inline modules/data-table/main/index.coffee]: Comments explaining what each of these arguments are could help

Comment (c-frater) [inline modules/data-table/main/index.coffee]: Makes sense - I'll do that now
