### PR TITLE
Meter fixes

### LINKED ISSUE #270: Meter: should emit an event on render
As the render is not handled explicitly by the user (i.e. render is called on resize), rendering the meter should emit an event.

### LINKED ISSUE #271: Meter: 'of' text is not localised
The `of 100` text displayed on the meter is not localised using `hx.userFacingText`

### LINKED ISSUE #272: Meter: add formatters for current/total value
Currently the values are displayed as passed in.
In some cases, the values need to be passed in as floating point numbers to display the meter accurately whilst the text values need to be rounded, it is currently not possible to do this.

### PR DESCRIPTION
**Pull request by jonthans**
fixed several issues for the meter
resolves #270
resolves #271
resolves #272

### CODE REVIEW

File: modules/meter/main/index.coffee [hunk 1]
```diff
@@ -64,7 +72,8 @@ class Meter
     else
       @_.data
 
-  render: ->
+  render: (cause) ->
+    cause ?= 'api'
```
Comment (georgesimms) [inline modules/meter/main/index.coffee]: Default argument instead ?
