### PR TITLE
#328: resolve the issue with the number picker

### LINKED ISSUE #159: Number Picker: disable the decrement/increment buttons when the value is at the min/max
This involves adding/removing the disabled attribute to the buttons when the value changes - currently the buttons just ignore input when they hit the limits

### LINKED ISSUE #328: NumberPicker: value is undefined in change event when typing in values
In Hexagon `1.5.1`:
- type any number - you receive single `change` event with that value when you leave the input
- type incorrect value - it is fixed when you leave the input

In Hexagon `1.7.0` (and probably `1.6.0`):
- type any number - you receive single `change` event with `undefined` as a value when you leave the input
- type incorrect value - it stays when you leave the input

### PR DESCRIPTION
**Pull request by c-frater**
Also, disable the buttons when the number picker reaches the min/max value 
Resolves #328 
Edit: also resolves #159 - I didn't realise there was an issue for it and just made the addition...

### CODE REVIEW

File: modules/number-picker/main/index.coffee [hunk 1]
```diff
@@ -72,27 +72,33 @@ class NumberPicker extends hx.EventEmitter
...
+        # If both value and screen value are defined, we set the input text to be the screen value
+        # otherwise we use the provided value (as it is set via the input)
+        .value(if value? and screenValue? then screenValue else newVal)
+
+      selection = hx.select(@selector)
+      selection.select('.hx-number-picker-decrement')
+        .attr('disabled', getDisabled(@options.disabled, newVal, @min()))
+
+      selection.select('.hx-number-picker-increment')
+        .attr('disabled', getDisabled(@options.disabled, newVal, @max()))
```
Comment (c-frater) [inline modules/number-picker/main/index.coffee]: Set the disabled state of the buttons whenever the value is updated

File: modules/number-picker/main/index.coffee [hunk 2]
```diff
@@ -72,27 +72,33 @@ class NumberPicker extends hx.EventEmitter
...
   value: (value, screenValue) ->
     if arguments.length > 0
       prevValue = @value()
-      newVal = if not value? and screenValue then screenValue else value
 
-      if @_.max isnt undefined and newVal > @_.max then newVal = @_.max
-      if @_.min isnt undefined and newVal < @_.min then newVal = @_.min
+      valueToUse = if not value? and screenValue then Number(screenValue) else value
+
+      newVal = checkValue(valueToUse, @min(), @max())
```
Comment (c-frater) [inline modules/number-picker/main/index.coffee]: I could probably use hx.clamp for this?

File: modules/number-picker/main/index.coffee [hunk 3]
```diff
@@ -72,27 +72,33 @@ class NumberPicker extends hx.EventEmitter
     if @options.max isnt undefined then @max @options.max
     if @options.min isnt undefined then @min @options.min
     if @options.disabled then @disabled(@options.disabled)
-
-    @selectInput
-      .attr('data-value', @options.value)
-      .value(@options.value)
+    @value @options.value
```
Comment (c-frater) [inline modules/number-picker/main/index.coffee]: We were setting the value from the constructor using the input which bypasses the checks inside the value method.
We may want to suppress the event here although you can't listen to it before this is fired so I'd say this is probably fine.

File: modules/number-picker/main/index.coffee [hunk 4]
```diff
@@ -62,8 +61,9 @@ class NumberPicker extends hx.EventEmitter
     @selectInput = selection.append('input')
     @selectInput.attr('type', 'number')
     @selectInput.on 'blur', 'hx.number-picker', =>
-      @emit 'input-change', {value: @value()}
-      @value(undefined, @selectInput.value())
+      if @selectInput.attr('readonly') is undefined
```
Comment (c-frater) [inline modules/number-picker/main/index.coffee]: The events were being fired when the input was readonly, causing issues with localised number values (e.g. time picker)

File: modules/number-picker/main/index.coffee (hunk 2 above)
Comment (jmsmyth) [inline modules/number-picker/main/index.coffee]: It would seem that hx.clamp doesn't handle undefined for min or max at the moment, so hx.clamp would need an upgrade to be used here

File: modules/number-picker/main/index.coffee [hunk 5]
```diff
@@ -101,7 +107,7 @@ class NumberPicker extends hx.EventEmitter
     if arguments.length > 0
       @_.min = val
       @selectInput.attr('min', val)
-      checkValue(this, this)
+      @value(@value())
```
Comment (jmsmyth) [inline modules/number-picker/main/index.coffee]: This looks odd.. Is is just to get events to fire or something?

Comment (c-frater) [inline modules/number-picker/main/index.coffee]: It's used to `clamp` the value - I guess we could check here if the value is smaller than the min and then do this but I figured as we do the check inside `@value` anyway it made sense to use it.
