### PR TITLE
401 data table advanced filter criteria

### LINKED ISSUE #401: DataTable: filter with advanced criteria
## Context

Currently when using the advanced search it is only possible to do `equals/contains` filtering. It would be nice to add in greater than, less than, doesn't contain etc. filter types.

This should probably be under `advancedSearchCriteria` and should only be applied to the advanced search. 

Applying it to the 'regular' filter would probably require the api to be changed as the current behaviour is to convert all the cell values to a single string and use a 'contains' filter for the search term. The filter types other than 'contains' would not work in this case without changing the api for the `filter` function in the feeds. 

The UI should probably just be a `Picker` with the different  [Filter](https://www.hexagonjs.io/docs/filter/) types available

### PR DESCRIPTION
**Pull request by c-frater**
## Description

- Added `hx.filter.types`, `hx.filter.stringTypes` and `hx.filter.numberTypes` to expose the lists of filters for other modules to use
- Added the ability to use the `hx.filter` types when using the advancedSearch
- Changed the UI to make the advanced search flow better on smaller devices

#### API Changes
```js
hx.DataTable::advancedSearchCriteria([subset of hx.filter.types]) // Set global
hx.DataTable::advancedSearchCriteria(columnId, [subset of hx.filter.types]) // Set column
```
Added `criteria` argument to `termLookup` function (defaults to `contains` for the defaultTermLookup)

## Motivation and Context

Resolves #401 

## How Has This Been Tested?

TODO

#### Compact Flow Any Column
Compact Flow Any Column

#### Compact Flow Column
Compact Flow Column

#### Full Table Any Column
Full Table Any Column

#### Full Table Column
Full Table Column

#### Full Table Flow Column
Full Table Flow Column

## Checklist:

- [x] I have added a tag to this pull request that indicates the impact of the change (patch, minor or major)
- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly. (This includes updating the changelog).
- [x] I have read the **CONTRIBUTING** document.
- [x] All my changes are covered by tests.
- [x] This request is ready to review and merge

### CODE REVIEW

File: modules/data-table/main/index.coffee [hunk 1]
```diff
@@ -27,6 +34,13 @@ columnOptionLookup = (options, name, id) ->
   else
     options[name]
 
+toCriteriaItems = (list) ->
+  new hx.Set(list).values().map (item) ->
```
Comment (jmsmyth) [inline modules/data-table/main/index.coffee]: Could also do `hx.unique(list).map (item) ->`

Comment (c-frater) [inline modules/data-table/main/index.coffee]: Wasn't aware of `hx.unique` - Missed it because it's so close to the bottom of the [Util](https://www.hexagonjs.io/docs/util/) api section...

File: modules/data-table/main/index.coffee [hunk 2]
```diff
@@ -168,42 +222,56 @@ createAdvancedSearchView = (selection, dataTable, options) ->
...
-      .component().value(if index is 0 then 'or' else 'and')
+    filterRowSel.select('.hx-data-table-advanced-search-type').component()
+      .value(if index is 0 then 'or' else 'and')
+
+    trueColumn = column or 'any'
+    filterRowSel.select('.hx-data-table-advanced-search-column').component()
+      .value(trueColumn)
+
+    columnCriteria = columnOptionLookup(options, 'advancedSearchCriteria', column) || []
+    criteriaItems = if trueColumn is 'any' then ['contains'] else ['contains', advancedSearchCriteriaValidate(columnCriteria)...]
```
Comment (c-frater) [inline modules/data-table/main/index.coffee]: I couldn't manage to get the `set` validation to work as expected because it treats `advancedSearchCriteria('something')` as `get value for column 'something'` so instead I've applied the validation logic when rendering the table - The value can be set to an invalid value but won't be rendered and will show a console warning

**Comment by c-frater** [comment]
Docs are in [Site #102](https://github.com/ocadotechnology/hexagonjs-site/pull/120)

File: modules/data-table/main/index.coffee [hunk 3]
```diff
@@ -27,6 +34,25 @@ columnOptionLookup = (options, name, id) ->
...
+toCriteriaItems = (list) ->
+  hx.unique(list).map (item) ->
+    {
+      value: item,
+      text: hx.userFacingText('dataTable', item)
+    }
+
+advancedSearchCriteriaValidate = (value) ->
+  allowedTypes = hx.filter.types()
+  if (hx.isArray(value) and value.every((c) -> ~allowedTypes.indexOf(c))) or value is undefined
```
Comment (jmsmyth) [inline modules/data-table/main/index.coffee]: Can this be changed to `>=0` or `!==-1` instead of tilde? More readable in my opinion

File: modules/data-table/main/index.coffee [hunk 4]
```diff
@@ -27,6 +34,25 @@ columnOptionLookup = (options, name, id) ->
...
+    value or []
+  else if hx.isArray(value)
+    invalidTypes = value.filter((c) -> not ~allowedTypes.indexOf(c))
```
Comment (jmsmyth) [inline modules/data-table/main/index.coffee]: Same thing with the `~` here

Comment (c-frater) [inline modules/data-table/main/index.coffee]: Sure - Noticed your comments after I hit merge....
I'll fix it on master
