### PR TITLE
#351 Inline editable enchancements

### LINKED ISSUE #351: InlineEditable: no way to edit empty string
If initial string is empty, it's not possible to edit it using InlineEditable component.

## Context
InlineEditable component ( https://www.hexagonjs.io/docs/1.8.2/inline-editable/ ).
Hexagon version 1.8.2 and early.

## Steps to Reproduce
1. Open the help page: https://www.hexagonjs.io/docs/1.8.2/inline-editable/
2. Click the "John Smith" string, input field is appeared. 
3. Replace "John Smith" to "" (empty string).
4. Save the change.

## Expected Behavior
When click the empty string, input field is appeared. 

## Actual Behavior
Nothing to click to show input field.

## Possible Fix
CSS rule:
```
a.hx-morph-toggle {
    min-width: 1em;
    min-height: 1em;
}
```

## Your Environment
* Hexagon Version: 1.8.2
* Browser Name and version: Google Chrome v54.0
* Operating System and version (desktop or mobile): MS Windows 7

### PR DESCRIPTION
**Pull request by c-frater**
## Description

- Added the `enterValueText` option to display when no value is entered (see screenshots)
- Added a `value` option (defaults to `selection.text()` as previous) 
  - This is so the value can  be set when using the fluid version
- Fixed the `change` event - it was passing `{api: false, value:<value>}` regardless of whether the value was set with the api or by the user (now uses standard `change/value` data)
- Added focus to the input when the editable is 'opened'
- Allow pressing `enter` to set the value
- Added tests for full coverage

## Motivation and Context

The initial scope of this was to resolve #351 but in the process of resolving it and adding tests I noticed a few other bugs

## How Has This Been Tested?

Added tests for full coverage of the module, tested on the demo page example

## Screenshots (if appropriate):
screen shot 2017-01-05 at 09 12 31
screen shot 2017-01-05 at 09 12 35
screen shot 2017-01-05 at 09 11 58
screen shot 2017-01-05 at 09 12 03

## Checklist:

- [x] I have added a tag to this pull request that indicates the impact of the change (patch, minor or major)
- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly. (This includes updating the changelog).
- [x] I have read the **CONTRIBUTING** document.
- [x] All my changes are covered by tests.
- [x] This request is ready to merge

### CODE REVIEW

File: modules/morph-section/main/index.coffee [hunk 1]
```diff
@@ -63,7 +63,7 @@ class InlineMorphSection extends MorphSection
         morphSection.detector = undefined
         morphSection.hide()
     @on 'hide', 'hx.morph-section', (data) ->
-      exitEditMode.call(morphSection, data.toggle, data.content)
+      exitEditMode?.call(morphSection, data.toggle, data.content)
```
Comment (c-frater) [inline modules/morph-section/main/index.coffee]: So you don't have to pass it through as an empty function if you don't have an exit edit mode function

File: modules/inline-editable/main/index.scss [hunk 2]
```diff
@@ -4,4 +4,8 @@
   .hx-input-group {
     margin: -0.45em 0;
   }
+}
+
+.hx-inline-editable-no-value {
+  font-style: italic;
```
Comment (c-frater) [inline modules/inline-editable/main/index.scss]: Making it italic when no value has been entered is probably enough of a visual cue (along with the `Enter Value` text) that the user should do something

File: modules/inline-editable/main/index.coffee [hunk 3]
```diff
@@ -1,32 +1,59 @@
...
+
 
-    super(@selector, enterEditMode, ->)
+    super(@selector, enterEditMode(options))
 
   value: (value) ->
     if value isnt undefined
       @textSelection.text(value)
-      @emit('change', {api: false, value: value})
+      @emit('change', { cause: 'api', value: value })
```
Comment (c-frater) [inline modules/inline-editable/main/index.coffee]: This was broken anyway (api was always passed as false) so I updated to the cause/value mentality.
